---
title: "C.shasta methylation analysis"
output: html_notebook
---


```{r}
#load methylKit package
library(methylKit)
```

```{r}
#specify directory of C.shasta BAM file
cshasta="/srv/WolfCloudNFS/HomeWolfCloud1033/rkyger/myxo-meth/1B-C-shasta_R1_val_1.fq.gz_unmapped_reads_1.fq.gz_unmapped_reads_1_bismark_pe.deduplicated.sorted.bam"
```


```{r}
#process Bismark BAM file for CpG methylation
cshasta.meth=processBismarkAln(location=cshasta, sample.id="cshasta", assembly="cs-assembly", save.folder = getwd(), save.context = c("CpG"), read.context = "CpG", nolap = TRUE, save.db = FALSE)
```


```{r}
#get CpG methylation stats for C.shasta
getMethylationStats(cshasta.meth, plot=FALSE, both.strands=FALSE)

#get histogram of CpG methylation for C.shasta
getMethylationStats(cshasta.meth, plot=TRUE, both.strands=FALSE)
```


```{r}
#get CpG coverage stats for C. shasta
getCoverageStats(cshasta.meth, plot=FALSE, both.strands=FALSE)

#get histogram of CpG coverage for C.shasta
getCoverageStats(cshasta.meth, plot=TRUE, both.strands=FALSE)
```


```{r}
#process Bismark BAM file for CHG methylation
cshasta.meth.CHG=processBismarkAln(location=cshasta, sample.id="cshasta", assembly="cs-assembly", save.folder = getwd(), save.context = c("CHG"), read.context = "CHG", nolap = TRUE, save.db = FALSE)
```


```{r}
#get CHG methylation stats for C.shasta
getMethylationStats(cshasta.meth.CHG, plot=FALSE, both.strands=FALSE)

#get histogram of CHG methylation for C.shasta
getMethylationStats(cshasta.meth.CHG,plot=TRUE,both.strands=FALSE)
```

```{r}
#get CHG coverage stats for C. shasta
getCoverageStats(cshasta.meth.CHG, plot=FALSE, both.strands=FALSE)

#get histogram of CHG coverage for C.shasta
getCoverageStats(cshasta.meth.CHG, plot=TRUE, both.strands=FALSE)
```


```{r}
#process Bismark BAM file for CHH methylation
cshasta.meth.CHH=processBismarkAln(location=cshasta, sample.id="cshasta", assembly="cs-assembly", save.folder = getwd(), save.context = c("CHH"), read.context = "CHH", nolap = TRUE, save.db = FALSE)
```

```{r}
#get CHH methylation stats for C.shasta
getMethylationStats(cshasta.meth.CHH, plot=FALSE, both.strands=FALSE)

#get histogram of CHH methylation for C.shasta
getMethylationStats(cshasta.meth.CHH, plot=TRUE, both.strands=FALSE)
```

```{r}
#get CHH coverage stats for C. shasta
getCoverageStats(cshasta.meth.CHH, plot=FALSE, both.strands=FALSE)

#get histogram of CHH coverage for C.shasta
getCoverageStats(cshasta.meth.CHH, plot=TRUE, both.strands=FALSE)
```

